Typos, Line Breaks
noisefloor/pytude pull request #3
Opened 2024-02-06 06:44 UTC by Hofei90

Typos, remove to many space and Line breaks inserted at 120 characters (in the file modules.md) for better readability in editors (PyCharm) The line breaks should not be visible in readthedocs, if this works I will submit this change for all other files later.

2024-02-06 11:51 UTC, Hofei90 commented on docs/modules.md
> +>> > import fibo
Hier ist mir ein Leerzeichen reingerutscht

2024-02-06 17:07 UTC, noisefloor commented on docs/modules.md
> +>> > import fibo
Bitte keine Zeilenumbrüche einfügen, wo diese nicht syntaktisch oder aufgrund der PEP8 notwendig sind. Der Text ist mit Absicht wie mit einer Textverarbeitung geschreiben, d.h. das ein Absatz keine Zeilenumbrüche enthält.

2024-02-06 17:19 UTC, noisefloor requested changes
Bitte keine Zeileumbrüche an Stellen, wo nicht zwingend welche hin müssen, einfügen. Das Dokument ist mit Absicht als Fließtext geschrieben.

2024-02-07 07:16 UTC, Hofei90 reviewed
Manuelle Zeilenumbrüche entfernt und Änderungen im Ausgabefenster rückgängig gemacht.

2024-02-07 07:16 UTC, Hofei90 commented on docs/modules.md
> +>> >
Hier ist mir ein Leerzeichen reingerutscht

2024-02-07 07:16 UTC, Hofei90 commented on docs/modules.md
> +>> > import fibo
Ich denke mal deine Anmerkung bezieht sich nicht auf das hier ausversehen zuviel getippte Leerzeichen, auf dem sich dieser Kommentar hier bezieht, sondern auf die allgemeine Formatierung der Datei modules.md

Die Änderung der Allgemeinen Formatierung ist in Arbeit.

2024-02-07 19:06 UTC, merged

2024-02-07 19:06 UTC, noisefloor commented
Genau, bezieht sich auf zusätzliche Zeilenumbrüche.